name: Run Blazor Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: .NET Setup Version
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.102'  # Ajusta si usas otra versión

      - name: Install dependencies
        run: dotnet restore

      - name: Build proyect
        run: dotnet build --configuration Release --no-restore

      - name: Execute Test
        run: dotnet test --configuration Release --no-build --logger trx --results-directory TestResults

      - name: Publish Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults
